# Generated by Django 4.0.4 on 2023-01-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_lecture_lecture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_date',
            new_name='date',
        ),
    ]
