# Generated by Django 4.0.4 on 2023-01-20 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_rename_lecture_date_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
