# Generated by Django 4.0.4 on 2023-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_lecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.TimeField(default='11:00'),
        ),
    ]
