# Generated by Django 4.0.4 on 2023-02-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_lecture_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(default='There is currently no description for this module', max_length=500),
        ),
    ]
