# Generated by Django 4.0.4 on 2023-02-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_module_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_data', models.TextField()),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.lecture')),
            ],
        ),
    ]
