# Generated by Django 4.0.4 on 2023-02-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_lecturerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'A'), ('Tuesday', 'B'), ('Wednesday', 'C'), ('Thursday', 'D'), ('Friday', 'E'), ('Saturday', 'F'), ('Sunday', 'G')], default='Monday', max_length=10),
        ),
    ]
