# Generated by Django 4.0.4 on 2023-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_lecture_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
