# Generated by Django 4.0.4 on 2023-02-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_alter_lecture_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
