# Generated by Django 4.0.4 on 2023-02-19 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_alter_lecture_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
